[package]
name = "mutica-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.4.1"
lalrpop-util = "0.22.2"
logos = "0.15.1"
stacksafe = "0.1.4"
mutica-core = { path = "../mutica-core" }

[build-dependencies]
lalrpop = "0.22.2"

[lib]
path = "src/lib.rs"
