[package]
name = "mutica"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
mutica-core = { path = "mutica-core" }
mutica-compiler = { path = "mutica-compiler" }
mutica-semantic = { path = "mutica-semantic" }

[[bin]]
name = "mutica"

[workspace]
members = ["mutica-core", "mutica-compiler", "mutica-semantic", "."]
