[package]
name = "mutica-semantic"

version.workspace = true
edition.workspace = true

[dependencies]
mutica-core = { workspace = true }
mutica-compiler = { workspace = true }

[lib]
path = "src/lib.rs"
