[package]
name = "mutica-semantic"
version = "0.1.0"
edition = "2024"

[dependencies]
mutica-core = { path = "../mutica-core" }
mutica-compiler = { path = "../mutica-compiler" }

[lib]
path = "src/lib.rs"
